In [1]:
import pandas as pd
import numpy as np

import joblib

In [2]:
train_df = pd.read_csv('../data/train.csv')
test_df = pd.read_csv('../data/test.csv')

In [3]:
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 594194 entries, 0 to 594193
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                594194 non-null  int64
 1   gender            594194 non-null  str
 2   SeniorCitizen     594194 non-null  int64
 3   Partner           594194 non-null  str
 4   Dependents        594194 non-null  str
 5   tenure            594194 non-null  int64
 6   PhoneService      594194 non-null  str
 7   MultipleLines     594194 non-null  str
 8   InternetService   594194 non-null  str
 9   OnlineSecurity    594194 non-null  str
 10  OnlineBackup      594194 non-null  str
 11  DeviceProtection  594194 non-null  str
 12  TechSupport       594194 non-null  str
 13  StreamingTV       594194 non-null  str
 14  StreamingMovies   594194 non-null  str
 15  Contract          594194 non-null  str
 16  PaperlessBilling  594194 non-null  str
 17  PaymentMethod     594194 non-null  str
 18  MonthlyCharges    594194 non-null  float64
 19  TotalCharges      594194 non-null  float64
 20  Churn             594194 non-null  str
dtypes: float64(2), int64(3), str(16)
memory usage: 95.2 MB

In [4]:
train_df.select_dtypes(include=np.number)

            id  SeniorCitizen  tenure  MonthlyCharges  TotalCharges
0            0              0      29           60.10       1653.85
1            1              0      58           69.50       3778.20
2            2              0      58          100.40       5841.35
3            3              0       1           69.70         70.70
4            4              0       1           70.45         70.45
...        ...            ...     ...             ...           ...
594189  594189              0      57           97.55       5460.70
594190  594190              0      72           91.95       6782.15
594191  594191              0      72           24.40       1871.90
594192  594192              0      32           86.00       2847.20
594193  594193              1       2           54.55        108.05

[594194 rows x 5 columns]

In [5]:
train_df.select_dtypes(exclude=np.number)

,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Churn
0,Male,Yes,Yes,Yes,No,DSL,Yes,No,Yes,Yes,No,No,One year,Yes,Mailed check,No
1,Male,Yes,Yes,Yes,No,DSL,Yes,Yes,No,Yes,Yes,No,Two year,No,Credit card (automatic),No
2,Male,Yes,No,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,No
3,Female,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,Yes
4,Female,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594189,Male,No,No,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Two year,No,Bank transfer (automatic),No
594190,Female,No,No,Yes,Yes,DSL,Yes,Yes,Yes,Yes,Yes,Yes,Two year,No,Bank transfer (automatic),No
594191,Female,Yes,No,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),No
594192,Female,No,No,Yes,Yes,Fiber optic,No,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,No
594193,Female,Yes,No,Yes,No,DSL,No,No,No,No,Yes,No,Month-to-month,Yes,Electronic check,Yes

In [6]:
target_col = 'Churn'

In [7]:
train_df[target_col].value_counts()

Churn
No     460377
Yes    133817
Name: count, dtype: int64

In [8]:
train_df[target_col] = train_df[target_col].map({"Yes": 1, "No": 0})
train_df[target_col].value_counts()

Churn
0    460377
1    133817
Name: count, dtype: int64

##### Creating a baseline Random Forest model strictly using numerical data

train df
keep numericals only
remove id 
remove churn from X, keep in y
train random forest

In [4]:
num_cols = train_df.select_dtypes(include=np.number).columns.to_list()
num_cols

['id', 'SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

In [10]:
X_train = train_df[[col for col in num_cols if col not in ['id', 'Churn']]]
y_train = train_df[target_col]

In [11]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
joblib.dump(rf, "../models/baseline_rf_num_only.joblib", compress=3)

['../models/baseline_rf_num_only.joblib']

In [3]:
rf = joblib.load("../models/baseline_rf_num_only.joblib")

In [13]:
test_df

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,594194,Female,0,Yes,No,72,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,115.55,8061.50
1,594195,Female,0,Yes,No,71,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),19.80,1336.50
2,594196,Male,0,No,No,12,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),55.55,633.55
3,594197,Male,0,Yes,Yes,71,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,Two year,No,Credit card (automatic),84.10,6457.15
4,594198,Female,0,No,No,15,Yes,No,Fiber optic,Yes,No,No,No,Yes,Yes,Month-to-month,No,Electronic check,90.35,1233.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254650,848844,Male,0,Yes,Yes,72,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),19.95,1443.65
254651,848845,Male,1,Yes,No,16,Yes,Yes,Fiber optic,No,No,No,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,100.15,1563.50
254652,848846,Male,0,Yes,No,35,Yes,Yes,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),105.80,3132.75
254653,848847,Female,0,No,No,25,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Credit card (automatic),20.25,511.25
254654,848848,Female,0,No,No,24,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),90.10,2172.05

In [5]:
X_test = test_df[[col for col in num_cols if col not in ['id', 'Churn']]]
X_test.head()

   SeniorCitizen  tenure  MonthlyCharges  TotalCharges
0              0      72          115.55       8061.50
1              0      71           19.80       1336.50
2              0      12           55.55        633.55
3              0      71           84.10       6457.15
4              0      15           90.35       1233.65

In [6]:
y_proba = rf.predict_proba(X_test)
y_proba

array([[0.996, 0.004],
       [1.   , 0.   ],
       [0.94 , 0.06 ],
       ...,
       [0.47 , 0.53 ],
       [1.   , 0.   ],
       [0.49 , 0.51 ]], shape=(254655, 2))

In [19]:
print(rf.classes_)

[0 1]

In [7]:
submission = test_df.copy()
submission['Churn'] = y_proba[:,1]
submission = submission[['id', 'Churn']]
submission.head()

       id  Churn
0  594194  0.004
1  594195  0.000
2  594196  0.060
3  594197  0.000
4  594198  0.880

In [9]:
submission.to_csv("../outputs/baseline_rf_num_only_submission.csv", index=False)

I see multiple categorical columns with Yes/No values. I can either use a categorical-friendly model, or I can convert the yes/no to numeric binary using
`df[<categorical_column>] = df[<categorical_column>].apply(lambda x: 1 if x=="Yes" else 0)` *(slower)* <br>
or <br>
`df.loc[df[<categorical_column>] == "Yes", <categorical_column>] = 1`

`df.loc[df[<categorical_column>] == "No", <categorical_column>] = 0` *(vectorized, faster)*
<br> or <br>
`df[<categorical_column>] = (df[<categorical_column>] == "Yes").astype(int) `

let's start with lightgbm

In [7]:
from lightgbm import LGBMClassifier

In [13]:
lgbm_base = LGBMClassifier()

lgbm_base.fit(X_train, y_train)

ValueError: pandas dtypes must be int, float or bool.
Fields with bad pandas dtypes: gender: str, Partner: str, Dependents: str, PhoneService: str, MultipleLines: str, InternetService: str, OnlineSecurity: str, OnlineBackup: str, DeviceProtection: str, TechSupport: str, StreamingTV: str, StreamingMovies: str, Contract: str, PaperlessBilling: str, PaymentMethod: str